### PR TITLE
Support using download attribute as file name

### PR DESCRIPTION
**Pull request by Trolleymusic**
Deals with issue https://github.com/jelmerdemaat/dwnld-attr-polyfill/issues/11

### CODE REVIEW

**Comment by Trolleymusic** [comment]
Could I get a review on this please @jelmerdemaat ?

**Comment by jelmerdemaat** [comment]
Great! I didn't know the download attribute could have a value. I thought it was a Boolean attribute.

**Review by jelmerdemaat — APPROVED** [review]

**Comment by Trolleymusic** [comment]
❤️ Let me know if I can do anything To help with merge and/or release

**Comment by jelmerdemaat** [comment]
I'm just wondering why the build checks won't complete... They have been stale since I first looked at this PR. I'm on a phone right now and not in a position to check this out. I'll check it out later, or maybe if you see why, feel free to comment on that.

**Comment by Trolleymusic** [comment]
I've just seen that on my fork the actions were disabled by default, so I've enabled the actions and force-pushed to kick off the checks. They've run ok https://github.com/Trolleymusic/dwnld-attr-polyfill/actions/runs/733850399.

Maybe they're not running because the checks are set to run on `push`, not `pull_request`, and there's been nothing pushed to this repo yet? 🤔 I'll add it to the actions and see if it helps.

**Comment by Trolleymusic** [comment]
Yeah, I've pushed that but it hasn't made a difference. You might add that change (https://github.com/jelmerdemaat/dwnld-attr-polyfill/pull/12/commits/c8aa7935b45a8b4bfdf40061cdf10a1df9d5336c) directly to your repo, and then I can close/reopen this PR and we can see if it runs then?

**Comment by jelmerdemaat** [comment]
Actually the checks have run, and passed now! Thanks! :)

**Pull request merged**
